// №4. Задачи Active Recall: выразить переменную.
// q — задание (LaTeX + текст), a — правильное выражение (LaTeX).
window.TASKS = [
  { q: "Выразите $t$ из $v = v_0 + a t$", a: "t = \\dfrac{v - v_0}{a}" },
  { q: "Выразите $a$ из $S = \\dfrac{v^2 - v_0^2}{2a}$", a: "a = \\dfrac{v^2 - v_0^2}{2S}" },
  { q: "Выразите $v_0$ из $S = \\dfrac{v + v_0}{2}\\,t$", a: "v_0 = \\dfrac{2S}{t} - v" },
  { q: "Выразите $h$ из $v = \\sqrt{2gh}$", a: "h = \\dfrac{v^2}{2g}" },
  { q: "Выразите $R$ из $a_n = \\dfrac{v^2}{R}$", a: "R = \\dfrac{v^2}{a_n}" },
  { q: "Выразите $T$ из $v = \\dfrac{2\\pi R}{T}$", a: "T = \\dfrac{2\\pi R}{v}" },
  { q: "Выразите $\\sin 2\\alpha$ из $L = \\dfrac{v_0^2 \\sin 2\\alpha}{g}$", a: "\\sin 2\\alpha = \\dfrac{L g}{v_0^2}" },
  { q: "Выразите $k$ из $T = 2\\pi\\sqrt{\\dfrac{m}{k}}$", a: "k = \\dfrac{4\\pi^2 m}{T^2}" },
  { q: "Выразите $g$ из $T = 2\\pi\\sqrt{\\dfrac{l}{g}}$", a: "g = \\dfrac{4\\pi^2 l}{T^2}" },
  { q: "Выразите $m$ из $F = G\\dfrac{M m}{r^2}$", a: "m = \\dfrac{F r^2}{G M}" },
  { q: "Выразите $r$ из $F = G\\dfrac{M m}{r^2}$", a: "r = \\sqrt{\\dfrac{G M m}{F}}" },
  { q: "Выразите $x$ из $F_{\\text{упр}} = k x$", a: "x = \\dfrac{F_{\\text{упр}}}{k}" },
  { q: "Выразите $v$ из $E_k = \\dfrac{m v^2}{2}$", a: "v = \\sqrt{\\dfrac{2 E_k}{m}}" },
  { q: "Выразите $h$ из $E_p = m g h$", a: "h = \\dfrac{E_p}{m g}" },
  { q: "Выразите $F$ из $A = F S \\cos\\alpha$", a: "F = \\dfrac{A}{S \\cos\\alpha}" },
  { q: "Выразите $t$ из $P = \\dfrac{A}{t}$", a: "t = \\dfrac{A}{P}" },
  { q: "Выразите $T$ из $p V = \\nu R T$", a: "T = \\dfrac{p V}{\\nu R}" },
  { q: "Выразите $V$ из $p V = \\nu R T$", a: "V = \\dfrac{\\nu R T}{p}" },
  { q: "Выразите $m$ из $\\nu = \\dfrac{m}{M}$", a: "m = \\nu M" },
  { q: "Выразите $\\Delta V$ из $A = p\\,\\Delta V$", a: "\\Delta V = \\dfrac{A}{p}" },
  { q: "Выразите $T_2$ из $\\eta = 1 - \\dfrac{T_2}{T_1}$", a: "T_2 = T_1 (1 - \\eta)" },
  { q: "Выразите $r$ из $F = k\\dfrac{|q_1 q_2|}{\\epsilon r^2}$", a: "r = \\sqrt{\\dfrac{k |q_1 q_2|}{\\epsilon F}}" },
  { q: "Выразите $U$ из $I = \\dfrac{U}{R}$", a: "U = I R" },
  { q: "Выразите $R$ из $I = \\dfrac{\\mathcal{E}}{R + r}$", a: "R = \\dfrac{\\mathcal{E}}{I} - r" },
  { q: "Выразите $C$ из $W = \\dfrac{C U^2}{2}$", a: "C = \\dfrac{2 W}{U^2}" },
  { q: "Выразите $S$ из $C = \\dfrac{\\epsilon \\epsilon_0 S}{d}$", a: "S = \\dfrac{C d}{\\epsilon \\epsilon_0}" },
  { q: "Выразите $B$ из $F_A = B I l \\sin\\alpha$", a: "B = \\dfrac{F_A}{I l \\sin\\alpha}" },
  { q: "Выразите $L$ из $W_M = \\dfrac{L I^2}{2}$", a: "L = \\dfrac{2 W_M}{I^2}" },
  { q: "Выразите $\\Delta t$ из $\\mathcal{E} = -\\dfrac{\\Delta \\Phi}{\\Delta t}$", a: "\\Delta t = -\\dfrac{\\Delta \\Phi}{\\mathcal{E}}" },
  { q: "Выразите $l$ из $T = 2\\pi\\sqrt{\\dfrac{l}{g}}$", a: "l = \\dfrac{g T^2}{4\\pi^2}" },
  { q: "Выразите $C$ из $T = 2\\pi\\sqrt{L C}$", a: "C = \\dfrac{T^2}{4\\pi^2 L}" },
  { q: "Выразите $F$ из $D = \\dfrac{1}{F}$", a: "F = \\dfrac{1}{D}" },
  { q: "Выразите $d$ из $d \\sin\\varphi = m \\lambda$", a: "d = \\dfrac{m \\lambda}{\\sin\\varphi}" },
  { q: "Выразите $\\lambda$ из $E = \\dfrac{h c}{\\lambda}$", a: "\\lambda = \\dfrac{h c}{E}" },
  { q: "Выразите $h$ из $E = h \\nu$", a: "h = \\dfrac{E}{\\nu}" }
];
